//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.Exchangings = new HashSet<Exchanging>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int id { get; set; }
        public int organizationCode { get; set; }
        public string name { get; set; }
        public int neighborhoodCode { get; set; }
        public string street { get; set; }
        public int buildingNumber { get; set; }
        public int ageCode { get; set; }
        public int genderCode { get; set; }
    
        public virtual Age Age { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Neighborhood Neighborhood { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exchanging> Exchangings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
