//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchanging
    {
        public int id { get; set; }
        public int classId { get; set; }
        public System.DateTime sourceDate { get; set; }
        public int teacherId { get; set; }
        public Nullable<int> substituteTeacherId { get; set; }
        public Nullable<System.DateTime> destinationDate { get; set; }
        public bool is_exchaning { get; set; }
        public int ask_id { get; set; }
        public bool is_relevant { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
